import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import HeroWithOverlay from "../components/HeroWithOverlay";
// Static DNA SVG background

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={"font-montserrat antialiased bg-black min-h-screen flex flex-col"}>
        <div style={{position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', zIndex: 0, pointerEvents: 'none', background: 'transparent'}} aria-hidden="true">
          <svg width="100%" height="100%" viewBox="0 0 1920 1080" fill="none" xmlns="http://www.w3.org/2000/svg" style={{width: '100vw', height: '100vh', display: 'block'}}>
            <polyline points="0,540 320,340 640,740 960,340 1280,740 1600,340 1920,540" stroke="#d946ef" strokeWidth="6" fill="none" opacity="0.18" />
            <polyline points="0,540 320,740 640,340 960,740 1280,340 1600,740 1920,540" stroke="#d946ef" strokeWidth="6" fill="none" opacity="0.18" />
            <g>
              {Array.from({length: 48}).map((_,i) => (
                <circle key={i} cx={40+i*40} cy={540+Math.sin(i/3)*200} r="7" fill="#d946ef" opacity="0.5" />
              ))}
            </g>
          </svg>
        </div>
        <main className="flex-1 flex flex-col bg-black relative z-10">
          <HeroWithOverlay />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
