import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import HeroWithOverlay from "../components/HeroWithOverlay";
import DNABackground from "../components/DNABackground";
import { usePathname } from "next/navigation";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  // Add bottom padding to main content only on main/hero page
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  const isOverlay = ["/about", "/contact", "/privacy-policy", "/terms"].includes(pathname);
  return (
    <html lang="en">
      <body className={"font-montserrat antialiased bg-black min-h-screen flex flex-col"}>
        <DNABackground />
        <main className={`flex-1 flex flex-col relative z-10 ${!isOverlay ? 'pb-32' : ''}`}>
          <HeroWithOverlay />
          {children}
        </main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
